title: Lifx Ambilight Addon for Kodi
description: Kodi add-on for Lifx lights with ambilight support.
google_analytics: UA-83116503-1
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
